language: python
python:
  - '2.7.6'
  - '3.5.0'
  - '3.7.0'

install:
  - 'travis_retry pip install .'
  - 'travis_retry pip install -e ".[test]"'

script: 
  - 'coverage run --source=src/onelogin/api --rcfile=tests/coverage.rc setup.py test'
  - 'coverage report -m --rcfile=tests/coverage.rc'
  - 'pep8 tests/src/onelogin/*.py --config=tests/pep8.rc'
  - 'pyflakes src/onelogin/api tests/src/oneLogin'

after_success: 'coveralls'
